---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: required

services:
  - docker

# Install ansible
addons:
  apt:
    packages:
    - python-pip

before_install:
  - docker pull clayman74/debian
  - sudo apt-get install -y sshpass

install:
  - export PYTHONPATH=/home/travis/virtualenv/python2.7.10/lib/python2.7/site-packages/:$PYTHONPATH

  # Install ansible
  - pip install ansible 'docker-py==1.9.0'

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - ansible-galaxy install clayman74.docker-provision --roles-path=tests/roles

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  - ansible-playbook tests/test.yml -i tests/inventory

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
