---

- name: Create network
  docker_network:
    name: "{{ consul_network }}"

- name: Pull image
  docker_image:
    name: "{{ consul_image }}"

- name: Start container
  docker_container:
    name: "{{ consul_container_name }}"
    image: "{{ consul_image }}"
    env:
      CONSUL_CLIENT_INTERFACE: "{{ consul_client_interface }}"
    log_driver: "{{ consul_log_driver }}"
    log_options: "{{ consul_log_options }}"
    networks:
      - name: "{{ consul_network }}"
    published_ports: "{{ consul_published_ports }}"
    restart_policy: "{{ consul_restart_policy }}"
    state: started
