---

- name: Create network
  docker_network:
    name: "{{ consul_network }}"

- name: Pull image
  docker_image:
    name: "{{ consul_image }}"

- name: Create container
  docker_container:
    name: "{{ consul_container_name }}"
    image: "{{ consul_image }}"
    state: started
    env:
      CONSUL_CLIENT_INTERFACE: eth0
    networks:
      - name: "{{ consul_network }}"
    published_ports:
      - 8500:8500
    restart_policy: always
